version: "2"
run:
  build-tags:
    - bench
    - ""
  tests: true
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goheader
    - goprintffuncname
    - gosec
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - tagliatelle
    - thelper
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    depguard:
      rules:
        Main:
          files:
            - $all
            - '!$test'
          allow:
            - $gostd
            - github.com/cheggaaa/pb/v3
            - github.com/BurntSushi/toml
            - github.com/jackc/pgx/stdlib
            - github.com/MAWINA-ant/hw-otus/hw12_13_14_15_calendar/internal/app
            - github.com/MAWINA-ant/hw-otus/hw12_13_14_15_calendar/internal/storage
            - github.com/MAWINA-ant/hw-otus/hw12_13_14_15_calendar/internal/logger
            - github.com/MAWINA-ant/hw-otus/hw12_13_14_15_calendar/internal/server/http
            - github.com/MAWINA-ant/hw-otus/hw12_13_14_15_calendar/internal/storage/sql
            - github.com/MAWINA-ant/hw-otus/hw12_13_14_15_calendar/internal/storage/memory
            - github.com/google/uuid
            - github.com/sirupsen/logrus
        Test:
          files:
            - $test
          allow:
            - $gostd
            - github.com/stretchr/testify
            - github.com/MAWINA-ant/hw-otus/hw12_13_14_15_calendar/internal/storage
            - github.com/MAWINA-ant/hw-otus/hw12_13_14_15_calendar/internal/storage/memory
            - github.com/google/uuid
            - github.com/sirupsen/logrus
    funlen:
      lines: 150
      statements: 80
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - errcheck
          - gocyclo
          - gosec
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
