title = "calendar service"

[logger]
level = "INFO"
file = "~/logs/calendar.txt"

[storage]
in-memory = true

[sql_storage]
host = ""
database = "databasename"
user = "username"
password = "password"

[server]
host = "127.0.0.1"
port = 12345

[grpc_server]
host = "127.0.0.1"
port = 12346